"""Core pipeline: claim issue -> workspace -> agent -> PR -> report."""

from __future__ import annotations

import logging

from jarvis.agent import run_agent
from jarvis.config import Config
from jarvis.db import Database
from jarvis.github_client import GitHubClient
from jarvis.models import IssueContext, RunStatus, Trigger
from jarvis.report import format_issue_report, format_failure_comment, format_success_comment
from jarvis.workspace import Workspace

log = logging.getLogger(__name__)


class Orchestrator:
    def __init__(self, config: Config) -> None:
        self.config = config
        self.db = Database(config.db_path)
        self.gh = GitHubClient(config)
        self.workspace = Workspace(config, self.gh.clone_url)

    def process_issue(self, issue: IssueContext, trigger: Trigger) -> None:
        run = self.db.create_run(issue.number, issue.title, trigger)
        run_id = run.id
        branch = self.workspace.branch_name(issue.number)

        try:
            self.db.update_run(run_id, status=RunStatus.RUNNING, branch=branch)

            # Setup workspace
            self.workspace.ensure_repo()
            self.workspace.create_branch(branch)

            # Run agent
            output = run_agent(self.config, issue, self.workspace.repo_dir)
            self.db.update_run(run_id, agent_output=output)

            # Commit and push
            commit_msg = f"fix: resolve issue #{issue.number} — {issue.title}"
            pushed = self.workspace.commit_and_push(branch, commit_msg)

            if not pushed:
                self.db.update_run(
                    run_id,
                    status=RunStatus.FAILED,
                    error="Agent produced no file changes",
                )
                comment = format_failure_comment(issue.number, "Agent produced no file changes")
                self.gh.comment_on_issue(issue.number, comment)
                return

            # Create PR
            pr_body = self._build_pr_body(issue, output)
            pr_url = self.gh.create_pr(
                branch=branch,
                title=f"fix: resolve #{issue.number} — {issue.title}",
                body=pr_body,
            )

            self.db.update_run(run_id, status=RunStatus.SUCCESS, pr_url=pr_url)
            self.gh.swap_labels(issue.number)

            comment = format_success_comment(issue.number, pr_url)
            self.gh.comment_on_issue(issue.number, comment)

            log.info("Issue #%d processed successfully: %s", issue.number, pr_url)

        except Exception as e:
            error_msg = str(e)
            log.error("Failed to process issue #%d: %s", issue.number, error_msg)
            self.db.update_run(run_id, status=RunStatus.FAILED, error=error_msg)

            try:
                comment = format_failure_comment(issue.number, error_msg)
                self.gh.comment_on_issue(issue.number, comment)
            except Exception:
                log.exception("Failed to comment on issue #%d", issue.number)

    def poll_once(self, trigger: Trigger = Trigger.POLL) -> int:
        issues = self.gh.get_labeled_issues()
        processed = 0

        for issue in issues:
            if self.db.is_issue_claimed(issue.number):
                log.debug("Issue #%d already claimed, skipping", issue.number)
                continue

            log.info("Processing issue #%d: %s", issue.number, issue.title)
            self.process_issue(issue, trigger)
            processed += 1

        return processed

    def run_single(self, issue_number: int, trigger: Trigger = Trigger.CLI) -> None:
        issue = self.gh.get_issue(issue_number)
        self.process_issue(issue, trigger)

    def _build_pr_body(self, issue: IssueContext, agent_output: str) -> str:
        # Truncate agent output if too long
        max_output = 3000
        output_excerpt = agent_output[:max_output]
        if len(agent_output) > max_output:
            output_excerpt += "\n\n... (truncated)"

        return f"""\
Closes #{issue.number}

## What this PR does
Automated fix for: **{issue.title}**

## Issue description
{issue.body[:1000] if issue.body else "No description provided."}

## Agent output
<details>
<summary>Click to expand</summary>

```
{output_excerpt}
```

</details>

---
*Generated by [Jarvis22](https://github.com/thangtruong/jarvis22)*
"""
